sign:
  head: '[machine]'
machine:
  block: IRON_BLOCK
  item: WOOD_SWORD
  usemodels: true
machines:
  table_saw:
    name: 'Table Saw'
    slug: 'saw'
    desc: 'A more-efficient way of cutting up your logs. Creates 2 times more planks then you get from vanilla crafting'
    takes: LOG
    makes: WOOD
    diff: 8
    damage: 2